apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "oai-nrf.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  {{- if .Values.global }}{{ if not .Values.global.clusterIpServiceIpAllocation }}
  clusterIP: None
  {{- end }}{{ end }}
  ports:
    - name: http
      # Port accessible outside cluster
      port: {{ .Values.exposedPorts.sbi }}
      # Port to forward config inside the pod
      targetPort: {{ .Values.exposedPorts.sbi }}
      protocol: TCP
  selector:
    {{- include "oai-nrf.selectorLabels" . | nindent 4 }}
